import Head from "next/head";
import React, { useState, setState } from "react";
import {
  Heading,
  Grid,
  Cell,
  Flex,
  Select,
} from "amazon-chime-sdk-component-library-react";
import { useTheme } from "styled-components";
import LoginWithCognito from "@/components/chat/LoginWithCognito";
import { useAuthContext } from "@/context/AuthProvider";

export default function Home() {
  const { userSignIn, userSignUp, userExchangeTokenForAwsCreds } =
    useAuthContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginWithCognito
          registe={(userName, password) => console.log(userName, password)}
          login={userSignIn}
        />
      </main>
    </>
  );
}
